"use client";

import Link from "next/link";
import GoogleMapPreview from "./GoogleMapPreview.jsx";
import SensoryIndicator from "./SensoryIndicator.jsx";

function arrival(minutes) { const date = new Date(Date.now() + Number(minutes || 0) * 60000); return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }

export default function CurrentTrip({ journey, congestion, lastCheckedAt, updating, refreshError, onPlan, onEnd }) {
  if (!journey) return <section className="current-trip-empty glass-panel"><p className="section-kicker">Journey status</p><h2>Current Trip</h2><p>No active trip.</p><button className="primary-button" type="button" onClick={onPlan}>Plan a journey</button></section>;
  const route = congestion ? { ...journey.route, sensory_score: congestion.sensory_score, sensory_indicator: congestion.sensory_indicator, data_freshness: congestion.data_freshness, updated_at: congestion.updated_at, route_segments: congestion.route_segments } : journey.route;
  return <div className="current-trip-layout"><section className="current-trip-card glass-panel"><div className="panel-heading"><div><p className="section-kicker">Active journey</p><h2>Current Trip</h2></div><span className="status-badge">Active</span></div><dl className="trip-metrics"><div><dt>Origin</dt><dd>{journey.origin.formattedAddress || journey.origin.label}</dd></div><div><dt>Destination</dt><dd>{journey.destination.formattedAddress || journey.destination.label}</dd></div><div><dt>Selected route</dt><dd>{route.route_identifier}</dd></div><div><dt>Sensory level</dt><dd><SensoryIndicator indicator={route.sensory_indicator} /></dd></div><div><dt>Congestion</dt><dd>{route.threshold_exceeded ? "Above your tolerance" : "Within your tolerance"}</dd></div><div><dt>Remaining time</dt><dd>{route.estimated_travel_minutes} minutes</dd></div><div><dt>Estimated arrival</dt><dd>{arrival(route.estimated_travel_minutes)}</dd></div><div><dt>Data freshness</dt><dd>{route.data_freshness || "unavailable"}</dd></div><div><dt>Last updated</dt><dd>{lastCheckedAt ? lastCheckedAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Waiting for update"}</dd></div><div><dt>Next instruction</dt><dd>{route.route_segments?.[0]?.instruction || "Continue along the selected route."}</dd></div></dl>{updating ? <p role="status">Updating congestion…</p> : null}{refreshError ? <p className="field-error">{refreshError} Last valid information remains visible.</p> : null}<div className="trip-actions"><button type="button" onClick={onPlan}>Review alternative</button><Link href="/refuges">Find nearby refuge</Link><button className="danger-button" type="button" onClick={onEnd}>End Trip</button></div></section><GoogleMapPreview routes={[route]} selectedRouteIdentifier={route.route_identifier} /></div>;
}
