param(
  [string]$OutputPath = "docs/security-plan-iteration-1.docx"
)

$ErrorActionPreference = "Stop"

function Escape-Xml([string]$Text) {
  return [System.Security.SecurityElement]::Escape($Text)
}

function Add-ParagraphXml {
  param(
    [System.Text.StringBuilder]$Builder,
    [string]$Text,
    [string]$Style = "BodyText"
  )
  $escaped = Escape-Xml $Text
  [void]$Builder.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"$Style`"/></w:pPr><w:r><w:t xml:space=`"preserve`">$escaped</w:t></w:r></w:p>")
}

function Add-BulletXml {
  param(
    [System.Text.StringBuilder]$Builder,
    [string]$Text
  )
  $escaped = Escape-Xml $Text
  [void]$Builder.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"ListParagraph`"/><w:numPr><w:ilvl w:val=`"0`"/><w:numId w:val=`"1`"/></w:numPr></w:pPr><w:r><w:t xml:space=`"preserve`">$escaped</w:t></w:r></w:p>")
}

function Add-TableRowXml {
  param(
    [System.Text.StringBuilder]$Builder,
    [string[]]$Cells
  )
  [void]$Builder.AppendLine("<w:tr>")
  foreach ($cell in $Cells) {
    $escaped = Escape-Xml $cell
    [void]$Builder.AppendLine("<w:tc><w:tcPr><w:tcW w:w=`"3333`" w:type=`"dxa`"/></w:tcPr><w:p><w:r><w:t xml:space=`"preserve`">$escaped</w:t></w:r></w:p></w:tc>")
  }
  [void]$Builder.AppendLine("</w:tr>")
}

$title = "eScape Security Plan Iteration 1"
$body = New-Object System.Text.StringBuilder

[void]$body.AppendLine("<w:document xmlns:w=`"http://schemas.openxmlformats.org/wordprocessingml/2006/main`">")
[void]$body.AppendLine("<w:body>")
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Title`"/></w:pPr><w:r><w:t>$([System.Security.SecurityElement]::Escape($title))</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">eScape is a sensory-aware navigation app for Melbourne CBD. This plan summarizes the current security posture, data handling, storage, and update process for the demo environment.</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>1. Project Overview</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">The application combines route planning, live crowd context, and nearby refuge discovery. It uses public open-data sources and local services, with a FastAPI backend and a Next.js frontend. The core demo does not require user accounts.</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>2. Data Handled by the System</w:t></w:r></w:p>")
@(
  "Journey inputs such as origin, destination, and crowd preference.",
  "Pedestrian-count data from City of Melbourne open-data sources.",
  "Route geometry and segment-level scoring for walking options.",
  "Refuge and point-of-interest data, including category, location, and opening hours where available.",
  "Prediction results and alert records generated by the backend."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>3. Where the Data Is Stored</w:t></w:r></w:p>")
@(
  "PostgreSQL stores route, sensor, refuge, prediction, and alert data.",
  "During development, PostgreSQL and OSRM run locally in Docker containers.",
  "FastAPI reads and writes data through the repository and service layers.",
  "Next.js renders the user interface and talks to the backend through the proxy."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>4. Update Frequency and Process</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:tbl><w:tblPr><w:tblW w:w=`"9000`" w:type=`"dxa`"/></w:tblPr><w:tblGrid><w:gridCol w:w=`"1800`"/><w:gridCol w:w=`"2200`"/><w:gridCol w:w=`"5000`"/></w:tblGrid>")
Add-TableRowXml -Builder $body -Cells @("Data","How Often It Changes","Update Process")
Add-TableRowXml -Builder $body -Cells @("Pedestrian counts","About every 15 minutes in production; refreshed at startup in the demo launcher.","Backend pulls from the City of Melbourne pedestrian-count API, validates readings, and upserts them into PostgreSQL.")
Add-TableRowXml -Builder $body -Cells @("Predictions","After each pedestrian refresh and then on a 10-15 minute schedule in production.","A backend job recomputes route and sensor predictions from current and historical counts.")
Add-TableRowXml -Builder $body -Cells @("Refuges","When the import script is run, typically manually or on a scheduled refresh.","Open-data sources are filtered, validated, and upserted into the point-of-interest tables.")
Add-TableRowXml -Builder $body -Cells @("Route options","On every journey submission.","FastAPI calculates route options, sensor matches, and sensory summaries for the selected trip.")
[void]$body.AppendLine("</w:tbl>")
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>5. Data Wrangling and Cleaning</w:t></w:r></w:p>")
@(
  "Coordinates are validated before storage.",
  "Duplicate records are updated instead of inserted again when a stable source identifier exists.",
  "Negative or malformed counts are rejected.",
  "Counts are normalized into low, medium, and high crowd categories.",
  "Route segments are matched to nearby sensors before scoring.",
  "Opening hours are only stored when they can be parsed reliably.",
  "Unconfirmed or incomplete refuge data is left as unavailable rather than guessed."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>6. Database Schema Summary</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">The underlying schema is documented in docs/database-schema.md. The high-level relationships are shown below.</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">user_preference -> journey_request -> route_option -> route_segment -> route_sensor_score</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">sensor_location -> historical_pedestrian_count</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">sensor_location -> realtime_pedestrian_count</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">sensor_location -> sensory_prediction -> alert</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">point_of_interest -> refuge_feedback</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>7. Security Controls</w:t></w:r></w:p>")
@(
  "The database and routing service stay local during development.",
  "Environment variables hold secrets and API keys.",
  "The frontend uses a proxy path to reach the backend instead of exposing internal ports.",
  "The public demo URL should go through Cloudflare rather than directly exposing the machine.",
  "The backend should fail gracefully if a source API is down."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>8. Risks and Limitations</w:t></w:r></w:p>")
@(
  "Open-data feeds may be stale or temporarily unavailable.",
  "Route quality depends on the current routing engine and source data.",
  "Refuge opening hours are incomplete for some places.",
  "Crowd levels are estimates and should be treated as guidance, not certainty.",
  "The current demo architecture is suitable for a class project but not yet for production-grade public exposure."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }
[void]$body.AppendLine("<w:p><w:pPr><w:pStyle w:val=`"Heading1`"/></w:pPr><w:r><w:t>9. Validation Checklist</w:t></w:r></w:p>")
@(
  "Confirm the database health endpoint is responding.",
  "Confirm pedestrian ingestion and refuge import can run from the launcher.",
  "Verify route planning still works after a reboot.",
  "Check that the Cloudflare tunnel only exposes the intended public surface.",
  "Keep the README and environment examples aligned with the running setup."
) | ForEach-Object { Add-BulletXml -Builder $body -Text $_ }

[void]$body.AppendLine("<w:p><w:r><w:t xml:space=`"preserve`">This document is a practical security summary for the eScape iteration demo and can be expanded into a formal submission if needed.</w:t></w:r></w:p>")
[void]$body.AppendLine("<w:sectPr><w:pgSz w:w=`"12240`" w:h=`"15840`"/><w:pgMar w:top=`"1440`" w:right=`"1440`" w:bottom=`"1440`" w:left=`"1440`"/></w:sectPr>")
[void]$body.AppendLine("</w:body></w:document>")

$styles = @"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:qFormat/>
    <w:rPr><w:sz w:val="22"/></w:rPr>
    <w:pPr><w:spacing w:after="120" w:line="276" w:lineRule="auto"/></w:pPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Title">
    <w:name w:val="Title"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:qFormat/>
    <w:rPr><w:b/><w:sz w:val="34"/></w:rPr>
    <w:pPr><w:spacing w:after="160"/></w:pPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:qFormat/>
    <w:rPr><w:b/><w:sz w:val="26"/><w:color w:val="17223B"/></w:rPr>
    <w:pPr><w:spacing w:before="240" w:after="100"/></w:pPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="BodyText">
    <w:name w:val="Body Text"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:qFormat/>
  </w:style>
  <w:style w:type="paragraph" w:styleId="ListParagraph">
    <w:name w:val="List Paragraph"/>
    <w:basedOn w:val="Normal"/>
    <w:next w:val="Normal"/>
    <w:pPr><w:ind w:left="720" w:hanging="360"/><w:spacing w:after="60"/></w:pPr>
  </w:style>
</w:styles>
"@

$numbering = @"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="0">
    <w:multiLevelType w:val="singleLevel"/>
    <w:lvl w:ilvl="0">
      <w:start w:val="1"/>
      <w:numFmt w:val="bullet"/>
      <w:lvlText w:val="•"/>
      <w:lvlJc w:val="left"/>
      <w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr>
      <w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/></w:rPr>
    </w:lvl>
  </w:abstractNum>
  <w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num>
</w:numbering>
"@

$contentTypes = @"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>
</Types>
"@

$rels = @"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="R1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
"@

$docRels = @"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="R2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="R3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>
</Relationships>
"@

$tmp = Join-Path $env:TEMP ("escape-security-plan-" + [guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $tmp | Out-Null
New-Item -ItemType Directory -Path (Join-Path $tmp "_rels") | Out-Null
New-Item -ItemType Directory -Path (Join-Path $tmp "word") | Out-Null
New-Item -ItemType Directory -Path (Join-Path $tmp "word/_rels") | Out-Null

[System.IO.File]::WriteAllText((Join-Path $tmp "[Content_Types].xml"), $contentTypes, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText((Join-Path $tmp "_rels/.rels"), $rels, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText((Join-Path $tmp "word/document.xml"), $body.ToString(), [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText((Join-Path $tmp "word/styles.xml"), $styles, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText((Join-Path $tmp "word/numbering.xml"), $numbering, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText((Join-Path $tmp "word/_rels/document.xml.rels"), $docRels, [System.Text.UTF8Encoding]::new($false))

if (Test-Path $OutputPath) { Remove-Item $OutputPath -Force }
if (Test-Path (Split-Path $OutputPath -Parent)) { } else { New-Item -ItemType Directory -Path (Split-Path $OutputPath -Parent) | Out-Null }

Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($tmp, $OutputPath)
Remove-Item $tmp -Recurse -Force

Write-Host "Created $OutputPath"
